version: '3.2'
services:
  blaze:
    image: "samply/blaze:0.8.0-beta.3"
    environment:
      BASE_URL: "http://localhost:8080"
      JAVA_TOOL_OPTIONS: "-Xms2g -Xmx2g -XX:+UseG1GC"
    ports:
    - "8080:8080"
    volumes:
    - "blaze-data:/app/data"
volumes:
  blaze-data:
